language: python
sudo: false

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/matplotlib

python:
  - 3.5
  - 3.6
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p ~/mc
  - export PATH=~/mc/bin:$PATH
  - conda config --set always_yes yes --set changeps1 no --set quiet true
  - conda config --add channels conda-forge
  - conda update conda --yes


install:
  - export GIT_FULL_HASH=`git rev-parse HEAD`
  - conda create --yes -n testenv python=$TRAVIS_PYTHON_VERSION orch
  - source activate testenv
  - orch score.yaml

script:
  - set -e
  - coverage run run_tests.py
  - coverage report -m
  - codecov
